import { StyleSheet } from 'react-native';
import { colors, shadows } from '../../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.neutral.white,
    borderRadius: 12,
    marginBottom: 16,
    ...shadows.medium,
  },
  cardContent: {
    flex: 1,
  },
  imageContainer: {
    position: 'relative',
    overflow: 'hidden',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: colors.neutral[50],
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  favoriteButton: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    ...shadows.small,
  },
  favoriteIcon: {
    fontSize: 14,
  },
  content: {
    padding: 12,
  },
  category: {
    color: colors.primary[500],
    fontWeight: '600',
    marginBottom: 4,
  },
  title: {
    color: colors.neutral[800],
    fontWeight: '600',
    marginBottom: 8,
    lineHeight: 20,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    color: colors.primary[600],
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'left',
  },
  rating: {
    backgroundColor: colors.neutral[100],
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  ratingText: {
    color: colors.primary,
    fontWeight: '600',
  },
  ratingAndQuantityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  topActionContainer: {
    padding: 12,
    paddingTop: 8,
    paddingBottom: 8,
    backgroundColor: colors.neutral[50],
    borderTopWidth: 1,
    borderTopColor: colors.neutral[200],
  },
  priceContainer: {
    padding: 12,
    paddingTop: 8,
    alignItems: 'flex-start',
    backgroundColor: colors.primary[50],
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.neutral.white,
    borderRadius: 6,
    paddingHorizontal: 4,
    minWidth: 70,
    justifyContent: 'space-between',
    height: 32,
    borderWidth: 1,
    borderColor: colors.neutral[200],
    ...shadows.small,
  },
  quantityButton: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    backgroundColor: colors.primary[100],
  },
  quantityButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.primary[500],
  },
  disabledText: {
    color: colors.neutral[400],
  },
  quantityText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.neutral[800],
    minWidth: 20,
    textAlign: 'center',
  },
  addToCartButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    ...shadows.small,
    borderWidth: 1,
    borderColor: colors.secondary_gray,
  },
  addToCartButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.secondary_gray,
  },
  addToCartIconActive: {
    fontSize: 16,
    color: colors.neutral.black,
  },
  addToCartTextActive: {
    color: colors.neutral.black,
    fontWeight: 'bold',
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    flex: 1,
    textAlign: 'center',
  },
  addToCartIcon: {
    fontSize: 16,
    color: colors.neutral.black,
  },
  addToCartText: {
    color: colors.neutral.black,
    fontWeight: 'bold',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    flex: 1,
    textAlign: 'center',
  },
  loadingCartButton: {
    opacity: 0.7,
    backgroundColor: colors.neutral[300],
  },
  loadingButton: {
    opacity: 0.6,
    backgroundColor: colors.neutral[200],
  },
  loadingText: {
    opacity: 0.7,
    color: colors.neutral[500],
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    zIndex: 1000,
  },
});